#All the cities I've ever known.
print('-' * 10, 'Trips', '-' * 10)
places = ['australia', 'united states', 'canada']
print('Number of records in the list:', len(places))
print(sorted(places))
print('-' * 30)
#Adding cities
places.append('brisbane')
places.append('sydney')
places.append('melbourne')
print(places[0].title(), '- We met in 2017.')
print('\t', places[3].title())
print('\t', places[4].title())
print('\t', places[5].title())
print('-' * 30)
print('Number of records in the list:', len(places))
print('-' * 30)
#Adding cities
places.append('new york')
places.append('houston')
print(places[1].title(), '- We met in 2019.')
print('\t', places[6].title())
print('\t', places[7].title())
print('-' * 30)
print('Number of records in the list:', len(places))
print('-' * 30)
#Adding cities
places.append('vancouver')
places.append('victoria')
places.append('toronto')
print(places[2].title(), '- We met in 2019.')
print('\t', places[8].title())
print('\t', places[9].title())
print('\t', places[10].title())
print('-' * 30)
#Full list
print('Number of records in the list:', len(places))
print('\n', sorted(places))
print('-' * 30)
print("I haven't seen the city of", places[10].title(), 'yet.')
del places[10]
print('-' * 30)
print('Updating cities in canada')
print('-' * 30)
print(places[2].title(), '- We met in 2019.')
print('\t', places[8].title())
print('\t', places[9].title())
print('-' * 30)
print('Number of records in the list:', len(places))
print('\n', sorted(places))
print('-' * 30)
