#Program that reads something through the keyboard and displays its primitive type and all possible information about it on the screen.
print('====== DEFIANCE 004 ======')
inf = input('Enter some information: ')
print('The information enter is type:', type(inf))
print('ALNUM:', inf.isalnum())
print('ALPHA:', inf.isalpha())
print('ASCII:', inf.isascii())
print('DECIMAL:', inf.isdecimal())
print('DIGIT:', inf.isdigit())
print('IDENTIFIER:', inf.isidentifier())
print('LOWER:', inf.islower())
print('NUMERIC:', inf.isnumeric())
print('PRINTABLE:', inf.isprintable())
print('SPACE:', inf.isspace())
print('TITLE:', inf.istitle())
print('UPPER:', inf.isupper())
